name: Anahtar yenile

on:
  schedule:
    - cron: "0 4 1 * *"
  workflow_dispatch:

jobs:
  yenile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm install libsodium-wrappers
      - env:
          INSTAGRAM_ACCESS_TOKEN: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
        run: node yenile.mjs
